### ISSUE TITLE
[BUG] Cannot save to relative filepath within folder

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/triad#74]
**Minimal Code To Reproduce**
```python
%%fsql
CREATE [[0,"hello"],[1,"world"]] SCHEMA number:int,word:str
SAVE OVERWRITE "/tmp/x.csv" (header=true)
```

**Describe the bug**
/tmp/ is not created in the current working directory and no error is raised. I can't find where fugue does save the file.

**Expected behavior**
x.csv is saved to the /tmp/ folder in the current working directory.

**Environment (please complete the following information):**
 - Backend: pandas
 - Backend version: 1.3.4
 - Python version: 3.9.7 
 - OS: OSX

<details>
<summary>environment.yml</summary>

```yml
name: budapestbi
channels:
  - conda-forge
  - defaults
dependencies:

  # notebook dependencies
  - pandas
  - dask
  - pyspark
  - dask-sql
  - scikit-learn  

  # fugue dependencies
  - triad
  - adagio
  - werkzeug
  - six
  - ciso8601
  - fs

  - pip
  - pip:
    - fugue[all]
```
</details>
